### PR TITLE
Allow haros to be run as part of run_tests.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

This is a draft as I'd like to discuss this first.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Follow-up / replacement for #11.

**Comment by gavanderhoorn** [comment]
This is indeed needed to get `haros_report()` to do anything at all in a test run, but I'm still not happy about it.

If we consider haros to be more akin to a 'documentation utility', then it shouldn't be run as part of `run_tests`, but either as a separate target (which we already add: `haros_report` and `haros_report_test_pkg`) or as part of some higher-level doc target.

**Comment by nlimpert** [comment]
Sorry for the late response - I'll see if I can verify the appropriate functionality with 
a7995fb .

**Review by nlimpert — APPROVED** [review]
Works! Thanks for the enhancement.

Tested with:
`catkin_make_isolated --catkin-make-args run_tests`

**Comment by gavanderhoorn** [comment]
> Works! Thanks for the enhancement.

That's great, but we really need a decision on #14.

**Comment by wasowski** [comment]
Starting to cleanup my github backlog.  Where we are on this? Is this at all relevant still?

**Comment by max-krichenbauer** [comment]
@wasowski I just found this thread as well and am a bit confused where it fits in the picture.
As far as I know:

(1) HAROS is now supposed to be used through a linter package (`haros_catkin`, `ament_haros` or `ament_cmake_haros`) which install HAROS through `catkin_virtualenv` or `ament_virtualenv` respectively. This part should already be working.

(2) There are PRs open on the [buildfarm](https://github.com/ros-infrastructure/ros_buildfarm/pull/685) and [wiki](https://github.com/droter/roswiki/pull/1) to show the resulting HAROS dashboard on the Wiki page, but it's uncertain if this will be accepted.

**Comment by wasowski** [comment]
What I suspect is that this project is now stale, and would be best deleted.  But @gavanderhoorn would know best ...

**Comment by gavanderhoorn** [comment]
We're not going to be doing this in this form any more, so closing.

**Pull request closed without merging**
